server:
  port: 9001

spring:
  application:
    name: g7auto
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public

springdoc:
  swagger-ui:
    path: /

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

admin:
  username: ${ADMIN_USERNAME}
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  hoTen: ${ADMIN_HO_TEN}

superadmin:
  username: ${SUPERADMIN_USERNAME}
  email: ${SUPERADMIN_EMAIL}
  password: ${SUPERADMIN_PASSWORD}
  full-name: ${SUPERADMIN_FULLNAME}
